[tools]
prek = { version = "0.4", postinstall = "prek install" }
age = "1.3"

[tasks.decrypt-secrets]
description = "Decrypt .secrets.yaml.age to .secrets.yaml"
run = "chezmoi decrypt .secrets.yaml.age --output .secrets.yaml"

[tasks.encrypt-secrets]
description = "Encrypt .secrets.yaml to .secrets.yaml.age and remove former"
run = "chezmoi encrypt .secrets.yaml --output .secrets.yaml.age && shred -n 30 -u -z .secrets.yaml"

[tasks.show-secrets]
description = "Show decrypted .secrets.yaml.age"
run = "chezmoi decrypt .secrets.yaml.age"
