#!/bin/zsh

bindkey -e
export EDITOR='nvim'
export XDG_CONFIG_HOME="$HOME/.config"
export GPG_TTY=$(tty)

#############
## PLUGINS ##
#############
source ~/.zplug/init.zsh

zplug "denysdovhan/spaceship-prompt", use:spaceship.zsh, as:theme
zplug "plugins/sudo", from:oh-my-zsh
zplug "plugins/ssh-agent", from:oh-my-zsh
zplug "agkozak/zsh-z"
zplug "zsh-users/zsh-syntax-highlighting", defer:2
zplug "amyreese/zsh-titles"

if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

zplug load

###############
## BEHAVIOUR ##
###############

# Prompt & completion
autoload -Uz compinit select-word-style edit-command-line
compinit
select-word-style bash
zle -N edit-command-line
ZSH_HIGHLIGHT_STYLES[comment]="fg=#71655a"

eval "$(atuin init zsh --disable-up-arrow)"

################
## KEYBINDING ##
################
bindkey '^[[3~' delete-char
bindkey '^[[Z'  reverse-menu-complete
bindkey '^V'    push-line
bindkey "^[[1;3C" forward-word
bindkey "^[[1;3D" backward-word
bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word
# bindkey '^[^?' backward-kill-word # previously ^H
bindkey '^X^E' edit-command-line


#############
## HISTORY ##
#############
HISTFILE=~/.zhistory
HISTSIZE=6000
SAVEHIST=5000
setopt INC_APPEND_HISTORY
setopt HIST_IGNORE_SPACE
setopt INTERACTIVE_COMMENTS
setopt HIST_IGNORE_DUPS
setopt HIST_EXPIRE_DUPS_FIRST # delete duplicates first

#############
## ALIASES ##
#############
alias ls='ls --color=auto'
alias grep='grep --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn}'
alias diff='diff --color=auto'
alias ll='ls -l'
alias la='ls -A'
alias lla='ls -lA'
alias vim='nvim'
alias v='nvim'
alias ssh='TERM=xterm-color; ssh'
alias copy='xclip -selection c'
alias l='exa'
alias nnn='nnn -e'
alias hx='helix'
alias k='kubectl'
alias tmp='cd $(mktemp -d)'
alias yk='ykman'
alias zed='zeditor'
alias cm='chezmoi'

#############
## SCRIPTS ##
#############
[ -d "$HOME/scripts" ] && PATH=$PATH:$HOME/scripts
[ -d "$HOME/go/bin" ] && PATH=$PATH:$HOME/go/bin
[ -d "$HOME/.dotnet" ] && PATH=$PATH:$HOME/.dotnet
[ -d "$HOME/.local/bin" ] && PATH=$PATH:$HOME/.local/bin
[ -d "$HOME/.cargo/bin" ] && PATH=$PATH:$HOME/.cargo/bin
[ -d "${KREW_ROOT:-$HOME/.krew}/bin" ] && PATH=$PATH:"${KREW_ROOT:-$HOME/.krew}/bin"
[ -d "$HOME/.radicle/bin" ] && PATH=$PATH:$HOME/.radicle/bin
[ -d "$HOME/.mammouth/bin" ] && PATH=$PATH:$HOME/.mammouth/bin

#############
## OPTIONS ##
#############
## Unset
unsetopt beep
## Set
setopt autocd
setopt interactivecomments


################
## COMPLETION ##
################
if command -v carapace &> /dev/null; then
    zstyle ':completion:*' format $'\e[2;37mCompleting %d\e[m'
    source <(carapace _carapace)
else
    zstyle :compinstall filename "$HOME/.zshrc"
    zstyle ':completion:*' menu select
    zstyle ':completion:*' list-suffixes
    zstyle ':completion:*' expand prefix suffix
    setopt COMPLETE_ALIASES
fi

# Broot
[ -f "$HOME/.config/broot/launcher/bash/br" ] && source $HOME/.config/broot/launcher/bash/br

###########
## FINAL ##
###########
export FZF_DEFAULT_OPTS="--layout=reverse --height 40%"
export SAM_CLI_TELEMETRY=0
export SPACESHIP_AZURE_SHOW=false
export MANPAGER="sh -c 'col -bx | bat -l man -p'"
export MANROFFOPT="-c"
export PATH
