#!/bin/zsh

bindkey -e
export EDITOR='nvim'
export XDG_CONFIG_HOME="$HOME/.config"
export GPG_TTY=$(tty)

###########
## PATHS ##
###########
[ -d "$HOME/scripts" ] && PATH="$PATH:$HOME/scripts"
[ -d "$HOME/go/bin" ] && PATH="$PATH:$HOME/go/bin"
[ -d "$HOME/.dotnet" ] && PATH="$PATH:$HOME/.dotnet"
[ -d "$HOME/.local/bin" ] && PATH="$PATH:$HOME/.local/bin"
[ -d "$HOME/.cargo/bin" ] && PATH="$PATH:$HOME/.cargo/bin"
[ -d "${KREW_ROOT:-$HOME/.krew}/bin" ] && PATH="$PATH:${KREW_ROOT:-$HOME/.krew}/bin"
[ -d "$HOME/.radicle/bin" ] && PATH="$PATH:$HOME/.radicle/bin"
[ -d "$HOME/.mammouth/bin" ] && PATH="$PATH:$HOME/.mammouth/bin"
[ -d "/home/linuxbrew/.linuxbrew/bin" ] && PATH="/home/linuxbrew/.linuxbrew/bin:$PATH" || ( [ -d "$HOME/.linuxbrew/bin" ] && PATH="$HOME/.linuxbrew/bin:$PATH" )


#############
## PLUGINS ##
#############

if command -v brew &> /dev/null; then
    source "$(brew --prefix)/opt/antidote/share/antidote/antidote.zsh" &>/dev/null && antidote load
fi

[ -f "$HOME/.config/zsh/sudo.zsh" ] && source "$HOME/.config/zsh/sudo.zsh"

###############
## BEHAVIOUR ##
###############
# Prompt & completion
autoload -Uz select-word-style edit-command-line
select-word-style bash
zle -N edit-command-line

################
## KEYBINDING ##
################
bindkey '^[[3~' delete-char
bindkey '^[[Z'  reverse-menu-complete
bindkey '^V'    push-line
bindkey "^[[1;3C" forward-word
bindkey "^[[1;3D" backward-word
bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word
bindkey '^X^E' edit-command-line


#############
## HISTORY ##
#############
HISTFILE=~/.zhistory
HISTSIZE=6000
SAVEHIST=5000
setopt INC_APPEND_HISTORY
setopt HIST_IGNORE_SPACE
setopt INTERACTIVE_COMMENTS
setopt HIST_IGNORE_DUPS
setopt HIST_EXPIRE_DUPS_FIRST # delete duplicates first

#############
## ALIASES ##
#############
alias ls='ls --color=auto'
alias grep='grep --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn}'
alias diff='diff --color=auto'
alias vim='nvim'
alias v='nvim'
alias ssh='TERM=xterm-color; ssh'
alias copy='xclip -selection c'
alias hx='helix'
alias k='kubectl'
alias tmp='cd $(mktemp -d)'
alias yk='ykman'
alias zed='zeditor'
alias cm='chezmoi'

#############
## OPTIONS ##
#############
## Unset
unsetopt beep
## Set
setopt autocd
setopt interactivecomments

##############
# INIT TOOLS #
##############

command -v brew &> /dev/null && export HOMEBREW_NO_ANALYTICS=1 && source <(command brew shellenv zsh)
command -v atuin &> /dev/null && source <(command atuin init zsh --disable-up-arrow)
command -v mise &> /dev/null && source <(command mise activate zsh)
command -v starship &> /dev/null && source <(command starship init zsh)


################
## COMPLETION ##
################
autoload -U compinit && compinit
if command -v carapace &> /dev/null; then
    zstyle ':completion:*' format $'\e[2;37mCompleting %d\e[m'
    source <(carapace _carapace)
else
    zstyle :compinstall filename "$HOME/.zshrc"
    zstyle ':completion:*' menu select
    zstyle ':completion:*' list-suffixes
    zstyle ':completion:*' expand prefix suffix
    setopt COMPLETE_ALIASES
fi

###########
## FINAL ##
###########
export FZF_DEFAULT_OPTS="--layout=reverse --height 40%"
export SAM_CLI_TELEMETRY=0
export MANPAGER="sh -c 'col -bx | bat -l man -p'"
export MANROFFOPT="-c"
export PATH
